name: CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          pip install -r ./main/requirements.txt
      - name: Run isort
        run: |
          isort --check-only ./main
      - name: Run black
        run: |
          black --diff --check ./main
      - name: Run mypy
        run: |
          mypy ./main
      - name: Run flake8
        run: |
          flake8 ../main
          
          
          
